# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "Capture beacon data from the browser, divert beacon request payloads to a log endpoint, and avoid putting load on your own infrastructure."
language = "rust"
manifest_version = 2
name = "Beacon termination"
service_id = ""

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
